# Generated by Django 2.2.7 on 2019-11-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lists',
            old_name='desctiption',
            new_name='descr',
        ),
    ]
