# Generated by Django 2.2.7 on 2019-11-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_item_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Lists',
        ),
    ]
