# Generated by Django 2.2.7 on 2019-11-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0004_auto_20191126_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('descr', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('detail', models.TextField(max_length=500)),
                ('done', models.BooleanField(default=False)),
                ('tdlst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Lists')),
            ],
        ),
    ]
